multipart:
    max-file-size: 5120Mb
    max-request-size: 5120Mb

server:
    port: 5005
    context-path: /qrcode
    
base-url: http://127.0.0.1:5006   

spring:
    thymeleaf:
        cache: false
        cache-period: 0
    template:
        cache: false
    mvc:
        favicon:
            enabled: false

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss # Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`.  
        joda-date-time-format: yyyy-MM-dd HH:mm:ss # Joda date time format string. If not configured, "date-format" will be used as a fallback if it is configured with a format string.  
        locale: zh_CN # Locale used for formatting.  
        time-zone: GMT+8 # Tim      

logging:
    level:
        root: INFO
    file: logs/qrcode-demo.log

#rest service configurations(TimeUnit: SECONDS)
connection-timeout: 10
read-timeout: 300
write-timeout: 10
