multipart:
    max-file-size: 5120Mb
    max-request-size: 5120Mb

server:
    port: 5005
    context-path: /qrcode

spring:
    thymeleaf:
        cache: false
        cache-period: 0
    template:
        cache: false
    mvc:
        favicon:
            enabled: false

    jackson:
        date-format: yyyy-MM-dd HH:mm:ss # Date format string or a fully-qualified date format class name. For instance `yyyy-MM-dd HH:mm:ss`.  
        joda-date-time-format: yyyy-MM-dd HH:mm:ss # Joda date time format string. If not configured, "date-format" will be used as a fallback if it is configured with a format string.  
        locale: zh_CN # Locale used for formatting.  
        time-zone: GMT+8 # Tim

logging:
    level:
        root: INFO
    file: logs/qrcode-demo.log

#rest service configurations(TimeUnit: SECONDS)
connection-timeout: 10
read-timeout: 300
write-timeout: 10

#layout
layout: content
full-layout: full-layout

database:
    host: localhost
    port: 3306
    name: qrcode_demo

spring:
    datasource:
        url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: toor
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 1000
        initialSize: 10
        maxWait: 60000
        minIdle: 5
        test-on-borrow: true 
        test-on-return: true
        validation-query: SELECT 1
        
    http:
        multipart:
            max-file-size: 5120Mb
            max-request-size: 5120Mb

mybatis: 
    mapperLocations: classpath:/com/cheng/base/mappers/*.xml
    typeAliasesPackage: com.cheng.test.domain
